/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import entities.ThemeFile;
import entities.sections.ControlPanelDesktop;
import entities.sections.Slideshow;
import entities.sections.Theme;
import entities.sections.VisualStyles;
import entities.utils.FileFilterObject;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JColorChooser;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import themeFileDao.ThemeFileDao;

/**
 *
 * @author Javier
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        lookAndFellSystem();
        initComponents();
        /*
        Theme theme = new Theme(txtDisplayName.getText(), txtBrandImage.getText(), null);
        ControlPanelDesktop cpd = new ControlPanelDesktop(txtWallpaper.getText(), cbTileWallpaper.isFocusOwner(), ControlPanelDesktop.WallpaperStyle.intToWallpaperStyle( Integer.parseInt( bgWallpaperStyle.getSelection().getActionCommand() ) ) );
        Slideshow slideshow = new Slideshow(Integer.parseInt(txtInterval.getText()), cbShuffle.isFocusOwner(), txtImagesRootPath.getText());
        VisualStyles visualStyles = new VisualStyles;
        setThemeFile(new ThemeFile);
        */
    }
    
    public ThemeFile getThemeFile(){
        return themeFile;
    }
    
    public void setThemeFile(ThemeFile tf){
        ThemeFile old = this.themeFile;
        this.themeFile = tf;
        firePropertyChange(PROP_THEMEFILE, old, tf);
    }
    
    public void setBrandImagePath( String path ){
        txtBrandImage.setText( path );
    }
    
    private void lookAndFellSystem(){
        try
	{
	    JFrame.setDefaultLookAndFeelDecorated(true);
	    JDialog.setDefaultLookAndFeelDecorated(true);
	    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName() );
	}
        catch(Exception ex){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bgWallpaperStyle = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtBrandImage = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbComposition = new javax.swing.JCheckBox();
        cbTransparency = new javax.swing.JCheckBox();
        PanelColorizationColor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNetwork = new javax.swing.JTextField();
        btnNetwork = new javax.swing.JButton();
        txtRecycleBin = new javax.swing.JTextField();
        btnRecycleBin = new javax.swing.JButton();
        txtComputer = new javax.swing.JTextField();
        btnComputer = new javax.swing.JButton();
        txtDocuments = new javax.swing.JTextField();
        btnDocuments = new javax.swing.JButton();
        txtDisplayName = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnAplicar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBrandImage = new javax.swing.JButton();
        tpWallpaper = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtWallpaper = new javax.swing.JTextField();
        btnWallpaper = new javax.swing.JButton();
        cbTileWallpaper = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        rbResized = new javax.swing.JRadioButton();
        rbCentered = new javax.swing.JRadioButton();
        rbTiled = new javax.swing.JRadioButton();
        rbStretched = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInterval = new javax.swing.JTextField();
        cbShuffle = new javax.swing.JCheckBox();
        txtImagesRootPath = new javax.swing.JTextField();
        btnImagesRootPath = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtBrandImage.setEditable(false);
        txtBrandImage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtBrandImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.theme.brandImage}"), txtBrandImage, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Visual Style", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel15.setText("Composition");

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel16.setText("Transparency");

        cbComposition.setBackground(new java.awt.Color(255, 255, 255));
        cbComposition.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbComposition.setAlignmentY(0.0F);
        cbComposition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbComposition.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbComposition.setMargin(new java.awt.Insets(10, 10, 10, 10));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.visualStyles.composition}"), cbComposition, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        cbTransparency.setBackground(new java.awt.Color(255, 255, 255));
        cbTransparency.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbTransparency.setAlignmentY(0.0F);
        cbTransparency.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbTransparency.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbTransparency.setMargin(new java.awt.Insets(10, 10, 10, 10));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.visualStyles.composition}"), cbTransparency, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        PanelColorizationColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelColorizationColor.setToolTipText("");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.visualStyles.colorizationColor}"), PanelColorizationColor, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        PanelColorizationColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelColorizationColorMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Colorization Color");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.visualStyles.colorizationColor}"), jLabel3, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout PanelColorizationColorLayout = new javax.swing.GroupLayout(PanelColorizationColor);
        PanelColorizationColor.setLayout(PanelColorizationColorLayout);
        PanelColorizationColorLayout.setHorizontalGroup(
            PanelColorizationColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelColorizationColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        PanelColorizationColorLayout.setVerticalGroup(
            PanelColorizationColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelColorizationColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(13, 13, 13)
                        .addComponent(cbComposition, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(10, 10, 10)
                        .addComponent(cbTransparency, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelColorizationColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(cbComposition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(cbTransparency))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PanelColorizationColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Display Name");

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("Brand Image");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Icons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setText("Computer");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setText("Recycle bin");

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel12.setText("Documents");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("Network");

        txtNetwork.setEditable(false);
        txtNetwork.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtNetwork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        btnNetwork.setBackground(new java.awt.Color(200, 220, 255));
        btnNetwork.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnNetwork.setText("...");
        btnNetwork.setMaximumSize(new java.awt.Dimension(41, 27));
        btnNetwork.setMinimumSize(new java.awt.Dimension(41, 27));
        btnNetwork.setPreferredSize(new java.awt.Dimension(41, 27));
        btnNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetworkActionPerformed(evt);
            }
        });

        txtRecycleBin.setEditable(false);
        txtRecycleBin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtRecycleBin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        btnRecycleBin.setBackground(new java.awt.Color(200, 220, 255));
        btnRecycleBin.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnRecycleBin.setText("...");
        btnRecycleBin.setMaximumSize(new java.awt.Dimension(41, 27));
        btnRecycleBin.setMinimumSize(new java.awt.Dimension(41, 27));
        btnRecycleBin.setPreferredSize(new java.awt.Dimension(41, 27));
        btnRecycleBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecycleBinActionPerformed(evt);
            }
        });

        txtComputer.setEditable(false);
        txtComputer.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtComputer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        btnComputer.setBackground(new java.awt.Color(200, 220, 255));
        btnComputer.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnComputer.setText("...");
        btnComputer.setMaximumSize(new java.awt.Dimension(41, 27));
        btnComputer.setMinimumSize(new java.awt.Dimension(41, 27));
        btnComputer.setPreferredSize(new java.awt.Dimension(41, 27));
        btnComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputerActionPerformed(evt);
            }
        });

        txtDocuments.setEditable(false);
        txtDocuments.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtDocuments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        btnDocuments.setBackground(new java.awt.Color(200, 220, 255));
        btnDocuments.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnDocuments.setText("...");
        btnDocuments.setMaximumSize(new java.awt.Dimension(41, 27));
        btnDocuments.setMinimumSize(new java.awt.Dimension(41, 27));
        btnDocuments.setPreferredSize(new java.awt.Dimension(41, 27));
        btnDocuments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRecycleBin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecycleBin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtRecycleBin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecycleBin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtComputer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComputer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDisplayName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtDisplayName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.theme.displayName}"), txtDisplayName, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtDisplayName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayNameActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(70, 70, 70));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAplicar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnAplicar.setForeground(new java.awt.Color(70, 70, 70));
        btnAplicar.setText("Aplicar");

        btnCancelar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnBrandImage.setBackground(new java.awt.Color(200, 220, 255));
        btnBrandImage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnBrandImage.setText("...");
        btnBrandImage.setMaximumSize(new java.awt.Dimension(41, 27));
        btnBrandImage.setMinimumSize(new java.awt.Dimension(41, 27));
        btnBrandImage.setPreferredSize(new java.awt.Dimension(41, 27));
        btnBrandImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandImageActionPerformed(evt);
            }
        });

        tpWallpaper.setBackground(new java.awt.Color(255, 255, 255));
        tpWallpaper.setToolTipText("");
        tpWallpaper.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tpWallpaper.setName(""); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("Tile Wallpaper");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setText("Wallpaper");

        txtWallpaper.setEditable(false);
        txtWallpaper.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtWallpaper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.controlPanelDesktop.wallpaper}"), txtWallpaper, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtWallpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWallpaperActionPerformed(evt);
            }
        });

        btnWallpaper.setBackground(new java.awt.Color(200, 220, 255));
        btnWallpaper.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnWallpaper.setText("...");
        btnWallpaper.setMaximumSize(new java.awt.Dimension(41, 27));
        btnWallpaper.setMinimumSize(new java.awt.Dimension(41, 27));
        btnWallpaper.setPreferredSize(new java.awt.Dimension(41, 27));
        btnWallpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWallpaperActionPerformed(evt);
            }
        });

        cbTileWallpaper.setBackground(new java.awt.Color(255, 255, 255));
        cbTileWallpaper.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbTileWallpaper.setAlignmentY(0.0F);
        cbTileWallpaper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbTileWallpaper.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbTileWallpaper.setMargin(new java.awt.Insets(10, 10, 10, 10));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.controlPanelDesktop.tileWallpaper}"), cbTileWallpaper, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Wallpaper Style", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 0, 12))); // NOI18N

        rbResized.setBackground(new java.awt.Color(255, 255, 255));
        bgWallpaperStyle.add(rbResized);
        rbResized.setText("Resized");

        rbCentered.setBackground(new java.awt.Color(255, 255, 255));
        bgWallpaperStyle.add(rbCentered);
        rbCentered.setText("Centered");
        rbCentered.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCenteredActionPerformed(evt);
            }
        });

        rbTiled.setBackground(new java.awt.Color(255, 255, 255));
        bgWallpaperStyle.add(rbTiled);
        rbTiled.setText("Tiled");

        rbStretched.setBackground(new java.awt.Color(255, 255, 255));
        bgWallpaperStyle.add(rbStretched);
        rbStretched.setText("Stretched");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbResized)
                    .addComponent(rbStretched)
                    .addComponent(rbTiled)
                    .addComponent(rbCentered))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(rbCentered)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbTiled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbStretched)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbResized)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTileWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbTileWallpaper))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpWallpaper.addTab("Wallpaper", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Interval");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Shuffle");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Images Root Path");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.slideshow.interval}"), txtInterval, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        txtInterval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntervalActionPerformed(evt);
            }
        });

        cbShuffle.setBackground(new java.awt.Color(255, 255, 255));
        cbShuffle.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        cbShuffle.setAlignmentY(0.0F);
        cbShuffle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cbShuffle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbShuffle.setMargin(new java.awt.Insets(10, 10, 10, 10));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.slideshow.shuffle}"), cbShuffle, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        txtImagesRootPath.setEditable(false);
        txtImagesRootPath.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txtImagesRootPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(130, 130, 130)));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${themeFile.slideshow.imagesRootPath}"), txtImagesRootPath, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnImagesRootPath.setBackground(new java.awt.Color(200, 220, 255));
        btnImagesRootPath.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnImagesRootPath.setText("...");
        btnImagesRootPath.setMaximumSize(new java.awt.Dimension(41, 27));
        btnImagesRootPath.setMinimumSize(new java.awt.Dimension(41, 27));
        btnImagesRootPath.setPreferredSize(new java.awt.Dimension(41, 27));
        btnImagesRootPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagesRootPathActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbShuffle, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInterval, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtImagesRootPath, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImagesRootPath, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(cbShuffle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImagesRootPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagesRootPath, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tpWallpaper.addTab("Slideshow", jPanel6);
        jPanel6.getAccessibleContext().setAccessibleName("");

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tpWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAbrir))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtBrandImage, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBrandImage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDisplayName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBrandImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrandImage, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tpWallpaper, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnAplicar)
                            .addComponent(btnCancelar)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tpWallpaper.getAccessibleContext().setAccessibleName("tpWallpaper");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDisplayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayNameActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //themeFile = new ThemeFile(new VisualStyles(), new ControlPanelDesktop(null, false, ControlPanelDesktop.WallpaperStyle.CENTERED));
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbCenteredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCenteredActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCenteredActionPerformed

    private void txtIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntervalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntervalActionPerformed

    private void btnBrandImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandImageActionPerformed
        ExtendedFileChooser jfc = getImageFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtBrandImage.setText( jfc.getSelectedFile().getAbsolutePath() );
        }     
    }//GEN-LAST:event_btnBrandImageActionPerformed

    private void btnNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetworkActionPerformed
        ExtendedFileChooser jfc = getIconsFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtNetwork.setText( jfc.getSelectedFile().getAbsolutePath() );
        }
    }//GEN-LAST:event_btnNetworkActionPerformed

    private void btnRecycleBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecycleBinActionPerformed
        ExtendedFileChooser jfc = getIconsFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtRecycleBin.setText( jfc.getSelectedFile().getAbsolutePath() );
        }
    }//GEN-LAST:event_btnRecycleBinActionPerformed

    private void btnComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputerActionPerformed
        ExtendedFileChooser jfc = getIconsFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtComputer.setText( jfc.getSelectedFile().getAbsolutePath() );
        }
    }//GEN-LAST:event_btnComputerActionPerformed

    private void btnDocumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentsActionPerformed
        ExtendedFileChooser jfc = getIconsFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtDocuments.setText( jfc.getSelectedFile().getAbsolutePath() );
        }
    }//GEN-LAST:event_btnDocumentsActionPerformed

    private void btnWallpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWallpaperActionPerformed
        ExtendedFileChooser jfc = getImageFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtWallpaper.setText( jfc.getSelectedFile().getAbsolutePath() );
        }
    }//GEN-LAST:event_btnWallpaperActionPerformed

    private void btnImagesRootPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagesRootPathActionPerformed
        ExtendedFileChooser jfc = getImageFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            txtImagesRootPath.setText( jfc.getSelectedFile().getAbsolutePath() );
        }
    }//GEN-LAST:event_btnImagesRootPathActionPerformed

    private void txtWallpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWallpaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWallpaperActionPerformed

    private void PanelColorizationColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelColorizationColorMouseClicked
        Color color = JColorChooser.showDialog(this, null, Color.red);
        PanelColorizationColor.setBackground(color);
    }//GEN-LAST:event_PanelColorizationColorMouseClicked

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        
        // Investigar binding de un buttonGroup(parece que hay que añadir el listener de forma manual)
        // UNA VEZ ECHO ESTO TODO DEVERÍA ESTAR TODO MENOS EL BOTÓN APLICAR Y LOS ICONOS DE LA PAPELERA(HAY QUE REVISAR THEMEFILEDAO)).
        
        ExtendedFileChooser jfc = getThemeFileChooser();
        
        if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            try{
                setThemeFile( ThemeFileDao.readThemeFile(jfc.getSelectedFile().getAbsolutePath()) );
            }catch( IOException e ){
                JOptionPane.showConfirmDialog(this, "Error a la hora de leer el fichero de tema", "Error de Lectura", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            ThemeFileDao.writeThemeFile(themeFile);
        }catch(IOException e){
            JOptionPane.showConfirmDialog(this, "Error a la hora de guardar el fichero de tema", "Error de Escritura", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private ExtendedFileChooser getIconsFileChooser(){
        ExtendedFileChooser fc = new ExtendedFileChooser();
        List<FileFilterObject> lffo = new ArrayList();
        
        lffo.add( FileFilterObject.Defaults.ICON.getValue() );
        
        fc.setFileFilterList(lffo);
        
        return fc;
    }
    
    private ExtendedFileChooser getImageFileChooser(){
        ExtendedFileChooser fc = new ExtendedFileChooser();
        List<FileFilterObject> lffo = new ArrayList();
        
        lffo.add( FileFilterObject.Defaults.IMAGES.getValue() );
        
        fc.setFileFilterList(lffo);
        
        return fc;
    }
    
    private ExtendedFileChooser getThemeFileChooser(){
        ExtendedFileChooser fc = new ExtendedFileChooser();
        List<FileFilterObject> lffo = new ArrayList();
        
        lffo.add( new FileFilterObject("Themes", "theme") );
        
        fc.setFileFilterList(lffo);
        
        return fc;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    public final static String PROP_THEMEFILE="themeFile";
    private ThemeFile themeFile = new ThemeFile();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelColorizationColor;
    private javax.swing.ButtonGroup bgWallpaperStyle;
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnBrandImage;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnComputer;
    private javax.swing.JButton btnDocuments;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImagesRootPath;
    private javax.swing.JButton btnNetwork;
    private javax.swing.JButton btnRecycleBin;
    private javax.swing.JButton btnWallpaper;
    private javax.swing.JCheckBox cbComposition;
    private javax.swing.JCheckBox cbShuffle;
    private javax.swing.JCheckBox cbTileWallpaper;
    private javax.swing.JCheckBox cbTransparency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rbCentered;
    private javax.swing.JRadioButton rbResized;
    private javax.swing.JRadioButton rbStretched;
    private javax.swing.JRadioButton rbTiled;
    private javax.swing.JTabbedPane tpWallpaper;
    private javax.swing.JTextField txtBrandImage;
    private javax.swing.JTextField txtComputer;
    private javax.swing.JTextField txtDisplayName;
    private javax.swing.JTextField txtDocuments;
    private javax.swing.JTextField txtImagesRootPath;
    private javax.swing.JTextField txtInterval;
    private javax.swing.JTextField txtNetwork;
    private javax.swing.JTextField txtRecycleBin;
    private javax.swing.JTextField txtWallpaper;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
